# Generated by Django 5.1.7 on 2025-04-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_company', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('educational_requirements', models.TextField(blank=True)),
                ('technical_requirements', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_qualifications', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('compensation', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, upload_to='job_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.company')),
            ],
        ),
    ]
